import React, { createContext, useState, useContext } from 'react';
const translations = {
  en: {
    smartAgri: "Smart Agriculture Platform",
    empoweringFarmers: "Empowering Farmers with AI-Driven Insights",
    transformFarming: "Transform your farming with data-driven decisions, real-time analytics, and intelligent crop recommendations",
    startAnalysis: "Start Analysis",
    learnMore: "Learn More",
    farmersHelped: "Farmers Helped",
    cropTypes: "Crop Types",
    accuracyRate: "Accuracy Rate",
    aiSupport: "AI Support",
    powerfulFeatures: "Powerful Features",
    cropPrediction: "Crop Prediction",
    cropPredictionDesc: "AI-powered recommendations based on soil parameters and weather conditions",
    soilAnalysis: "Soil Analysis",
    soilAnalysisDesc: "Comprehensive soil health assessment with NPK levels and pH monitoring",
    fertilizerGuide: "Fertilizer Guide",
    fertilizerGuideDesc: "Personalized fertilizer recommendations for optimal crop growth",
    analyticsDashboard: "Analytics Dashboard",
    analyticsDashboardDesc: "Track your farming history and monitor crop performance over time",
    readyToTransform: "Ready to Transform Your Farm?",
    joinThousands: "Join thousands of farmers using AI to maximize their harvest",
    getStartedNow: "Get Started Now",
    dashboard: "Dashboard",
    analysis: "Analysis",
    analytics: "Analytics",
    history: "History",
    about: "About",
    logout: "Logout",
    cropAnalysis: "Crop Photo Analysis",
    howToUse: "How to Use:",
    step1: "Take a clear photo of your crop or field",
    step2: "Click the button below to upload",
    step3: "Get instant fertilizer & care advice",
    takePhoto: "Take/Upload Photo",
    changePhoto: "Change Photo",
    analyzing: "Analyzing...",
    analyzeCrop: "Analyze Crop",
    fertilizerNeeded: "Fertilizer Needed:",
    waterRequirement: "Water Requirement:",
    plantingSeason: "Planting Season:",
    expertAdvice: "Expert Advice:",
    chatAssistant: "Crop Assistant",
    askAboutCrops: "Ask about crops...",
    send: "Send",
    predictCrop: "Predict Crop",
    recommendedCrop: "Recommended Crop",
    cropInfoGuide: "Crop Information Guide",
    season: "Season",
    temperature: "Temperature",
    rainfall: "Rainfall",
    soilType: "Soil Type",
    npkRatio: "NPK Ratio",
    duration: "Duration",
    expectedYield: "Expected Yield",
    commonDiseases: "Common Diseases",
    farmingTips: "Farming Tips"
  },
  hi: {
    smartAgri: "स्मार्ट कृषि मंच",
    empoweringFarmers: "AI-संचालित अंतर्दृष्टि के साथ किसानों को सशक्त बनाना",
    transformFarming: "डेटा-संचालित निर्णयों, रीयल-टाइम विश्लेषण और बुद्धिमान फसल सिफारिशों के साथ अपनी खेती को बदलें",
    startAnalysis: "विश्लेषण शुरू करें",
    learnMore: "और जानें",
    farmersHelped: "किसानों की मदद की",
    cropTypes: "फसल के प्रकार",
    accuracyRate: "सटीकता दर",
    aiSupport: "AI सहायता",
    powerfulFeatures: "शक्तिशाली सुविधाएँ",
    cropPrediction: "फसल भविष्यवाणी",
    cropPredictionDesc: "मिट्टी के मापदंडों और मौसम की स्थिति के आधार पर AI-संचालित सिफारिशें",
    soilAnalysis: "मिट्टी विश्लेषण",
    soilAnalysisDesc: "NPK स्तर और pH निगरानी के साथ व्यापक मिट्टी स्वास्थ्य मूल्यांकन",
    fertilizerGuide: "उर्वरक गाइड",
    fertilizerGuideDesc: "इष्टतम फसल वृद्धि के लिए व्यक्तिगत उर्वरक सिफारिशें",
    analyticsDashboard: "विश्लेषण डैशबोर्ड",
    analyticsDashboardDesc: "अपने खेती के इतिहास को ट्रैक करें और समय के साथ फसल के प्रदर्शन की निगरानी करें",
    readyToTransform: "अपने खेत को बदलने के लिए तैयार हैं?",
    joinThousands: "अपनी फसल को अधिकतम करने के लिए AI का उपयोग करने वाले हजारों किसानों में शामिल हों",
    getStartedNow: "अभी शुरू करें",
    dashboard: "डैशबोर्ड",
    analysis: "विश्लेषण",
    analytics: "विश्लेषिकी",
    history: "इतिहास",
    about: "के बारे में",
    logout: "लॉग आउट",
    cropAnalysis: "फसल फोटो विश्लेषण",
    howToUse: "कैसे उपयोग करें:",
    step1: "अपनी फसल या खेत की स्पष्ट तस्वीर लें",
    step2: "अपलोड करने के लिए नीचे बटन पर क्लिक करें",
    step3: "तुरंत उर्वरक और देखभाल सलाह प्राप्त करें",
    takePhoto: "फोटो लें/अपलोड करें",
    changePhoto: "फोटो बदलें",
    analyzing: "विश्लेषण हो रहा है...",
    analyzeCrop: "फसल का विश्लेषण करें",
    fertilizerNeeded: "आवश्यक उर्वरक:",
    waterRequirement: "पानी की आवश्यकता:",
    plantingSeason: "बुवाई का मौसम:",
    expertAdvice: "विशेषज्ञ सलाह:",
    chatAssistant: "फसल सहायक",
    askAboutCrops: "फसलों के बारे में पूछें...",
    send: "भेजें",
    predictCrop: "फसल की भविष्यवाणी करें",
    recommendedCrop: "अनुशंसित फसल",
    cropInfoGuide: "फसल जानकारी गाइड",
    season: "मौसम",
    temperature: "तापमान",
    rainfall: "वर्षा",
    soilType: "मिट्टी का प्रकार",
    npkRatio: "NPK अनुपात",
    duration: "अवधि",
    expectedYield: "अपेक्षित उपज",
    commonDiseases: "सामान्य रोग",
    farmingTips: "खेती के सुझाव"
  },
  te: {
    smartAgri: "స్మార్ట్ వ్యవసాయ వేదిక",
    empoweringFarmers: "AI-ఆధారిత అంతర్దృష్టులతో రైతులకు శక్తినిస్తోంది",
    transformFarming: "డేటా-ఆధారిత నిర్ణయాలు, రియల్-టైమ్ విశ్లేషణలు మరియు తెలివైన పంట సిఫార్సులతో మీ వ్యవసాయాన్ని మార్చండి",
    startAnalysis: "విశ్లేషణ ప్రారంభించండి",
    learnMore: "మరింత తెలుసుకోండి",
    farmersHelped: "రైతులకు సహాయం చేసారు",
    cropTypes: "పంట రకాలు",
    accuracyRate: "ఖచ్చితత్వ రేటు",
    aiSupport: "AI మద్దతు",
    powerfulFeatures: "శక్తివంతమైన లక్షణాలు",
    cropPrediction: "పంట అంచనా",
    cropPredictionDesc: "నేల పారామితులు మరియు వాతావరణ పరిస్థితుల ఆధారంగా AI-శక్తితో కూడిన సిఫార్సులు",
    soilAnalysis: "నేల విశ్లేషణ",
    soilAnalysisDesc: "NPK స్థాయిలు మరియు pH పర్యవేక్షణతో సమగ్ర నేల ఆరోగ్య అంచనా",
    fertilizerGuide: "ఎరువుల మార్గదర్శి",
    fertilizerGuideDesc: "సరైన పంట పెరుగుదల కోసం వ్యక్తిగత ఎరువుల సిఫార్సులు",
    analyticsDashboard: "విశ్లేషణ డాష్‌బోర్డ్",
    analyticsDashboardDesc: "మీ వ్యవసాయ చరిత్రను ట్రాక్ చేయండి మరియు కాలక్రమేణా పంట పనితీరును పర్యవేక్షించండి",
    readyToTransform: "మీ పొలాన్ని మార్చడానికి సిద్ధంగా ఉన్నారా?",
    joinThousands: "మీ పంటను పెంచడానికి AIని ఉపయోగిస్తున్న వేలాది మంది రైతులతో చేరండి",
    getStartedNow: "ఇప్పుడే ప్రారంభించండి",
    dashboard: "డాష్‌బోర్డ్",
    analysis: "విశ్లేషణ",
    history: "చరిత్ర",
    about: "గురించి",
    logout: "లాగ్ అవుట్",
    cropAnalysis: "పంట ఫోటో విశ్లేషణ",
    howToUse: "ఎలా ఉపయోగించాలి:",
    step1: "మీ పంట లేదా పొలం యొక్క స్పష్టమైన ఫోటో తీయండి",
    step2: "అప్‌లోడ్ చేయడానికి క్రింద ఉన్న బటన్‌ను క్లిక్ చేయండి",
    step3: "తక్షణ ఎరువులు మరియు సంరక్షణ సలహా పొందండి",
    takePhoto: "ఫోటో తీయండి/అప్‌లోడ్ చేయండి",
    changePhoto: "ఫోటో మార్చండి",
    analyzing: "విశ్లేషిస్తోంది...",
    analyzeCrop: "పంట విశ్లేషణ",
    fertilizerNeeded: "అవసరమైన ఎరువులు:",
    waterRequirement: "నీటి అవసరం:",
    plantingSeason: "నాటే కాలం:",
    expertAdvice: "నిపుణుల సలహా:",
    chatAssistant: "పంట సహాయకుడు",
    askAboutCrops: "పంటల గురించి అడగండి...",
    send: "పంపండి",
    predictCrop: "పంట అంచనా",
    recommendedCrop: "సిఫార్సు చేయబడిన పంట",
    cropInfoGuide: "పంట సమాచార మార్గదర్శి",
    season: "కాలం",
    temperature: "ఉష్ణోగ్రత",
    rainfall: "వర్షపాతం",
    soilType: "నేల రకం",
    npkRatio: "NPK నిష్పత్తి",
    duration: "వ్యవధి",
    expectedYield: "ఆశించిన దిగుబడి",
    commonDiseases: "సాధారణ వ్యాధులు",
    farmingTips: "వ్యవసాయ చిట్కాలు"
  },
  ta: {
    smartAgri: "ஸ்மார்ட் விவசாய தளம்",
    empoweringFarmers: "AI-இயக்கப்படும் நுண்ணறிவுகளுடன் விவசாயிகளுக்கு அதிகாரம் அளித்தல்",
    transformFarming: "தரவு-இயக்கப்படும் முடிவுகள், நிகழ்நேர பகுப்பாய்வு மற்றும் அறிவார்ந்த பயிர் பரிந்துரைகளுடன் உங்கள் விவசாயத்தை மாற்றுங்கள்",
    startAnalysis: "பகுப்பாய்வைத் தொடங்கு",
    learnMore: "மேலும் அறிக",
    farmersHelped: "விவசாயிகளுக்கு உதவியது",
    cropTypes: "பயிர் வகைகள்",
    accuracyRate: "துல்லிய விகிதம்",
    aiSupport: "AI ஆதரவு",
    powerfulFeatures: "சக்திவாய்ந்த அம்சங்கள்",
    cropPrediction: "பயிர் கணிப்பு",
    cropPredictionDesc: "மண் அளவுருக்கள் மற்றும் வானிலை நிலைமைகளின் அடிப்படையில் AI-இயக்கப்படும் பரிந்துரைகள்",
    soilAnalysis: "மண் பகுப்பாய்வு",
    soilAnalysisDesc: "NPK நிலைகள் மற்றும் pH கண்காணிப்புடன் விரிவான மண் ஆரோக்கிய மதிப்பீடு",
    fertilizerGuide: "உர வழிகாட்டி",
    fertilizerGuideDesc: "உகந்த பயிர் வளர்ச்சிக்கான தனிப்பயனாக்கப்பட்ட உர பரிந்துரைகள்",
    analyticsDashboard: "பகுப்பாய்வு டாஷ்போர்டு",
    analyticsDashboardDesc: "உங்கள் விவசாய வரலாற்றைக் கண்காணித்து காலப்போக்கில் பயிர் செயல்திறனைக் கண்காணிக்கவும்",
    readyToTransform: "உங்கள் பண்ணையை மாற்ற தயாரா?",
    joinThousands: "உங்கள் அறுவடையை அதிகரிக்க AI ஐப் பயன்படுத்தும் ஆயிரக்கணக்கான விவசாயிகளுடன் சேரவும்",
    getStartedNow: "இப்போதே தொடங்குங்கள்",
    dashboard: "டாஷ்போர்டு",
    analysis: "பகுப்பாய்வு",
    history: "வரலாறு",
    about: "பற்றி",
    logout: "வெளியேறு",
    cropAnalysis: "பயிர் புகைப்பட பகுப்பாய்வு",
    howToUse: "எப்படி பயன்படுத்துவது:",
    step1: "உங்கள் பயிர் அல்லது வயலின் தெளிவான புகைப்படம் எடுக்கவும்",
    step2: "பதிவேற்ற கீழே உள்ள பொத்தானை கிளிக் செய்யவும்",
    step3: "உடனடி உரம் மற்றும் பராமரிப்பு ஆலோசனை பெறவும்",
    takePhoto: "புகைப்படம் எடு/பதிவேற்று",
    changePhoto: "புகைப்படத்தை மாற்று",
    analyzing: "பகுப்பாய்வு செய்கிறது...",
    analyzeCrop: "பயிரை பகுப்பாய்வு செய்",
    fertilizerNeeded: "தேவையான உரம்:",
    waterRequirement: "நீர் தேவை:",
    plantingSeason: "விதைப்பு பருவம்:",
    expertAdvice: "நிபுணர் ஆலோசனை:",
    chatAssistant: "பயிர் உதவியாளர்",
    askAboutCrops: "பயிர்கள் பற்றி கேளுங்கள்...",
    send: "அனுப்பு",
    predictCrop: "பயிர் கணிப்பு",
    recommendedCrop: "பரிந்துரைக்கப்பட்ட பயிர்",
    cropInfoGuide: "பயிர் தகவல் வழிகாட்டி",
    season: "பருவம்",
    temperature: "வெப்பநிலை",
    rainfall: "மழைப்பொழிவு",
    soilType: "மண் வகை",
    npkRatio: "NPK விகிதம்",
    duration: "காலம்",
    expectedYield: "எதிர்பார்க்கப்படும் விளைச்சல்",
    commonDiseases: "பொதுவான நோய்கள்",
    farmingTips: "விவசாய குறிப்புகள்"
  }
};
const LanguageContext = createContext();
export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(localStorage.getItem('language') || 'en');
  const changeLanguage = (lang) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };
  const t = (key) => translations[language][key] || key;
  return (
    <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
export const useLanguage = () => useContext(LanguageContext);

// Analytics translations added
translations.en.analytics = "Analytics";
translations.hi.analytics = "विश्लेषिकी";
translations.te.analytics = "విశ్లేషణలు";
translations.ta.analytics = "பகுப்பாய்வு";
